# Generated by Django 5.0.6 on 2026-05-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='pagado',
            field=models.BooleanField(default=True, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='inventario.cliente', verbose_name='Cliente (cuenta)'),
        ),
    ]
