# Generated by Django 5.0.6 on 2026-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_cliente_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
