# Generated by Django 5.2.11 on 2026-05-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Efectivo ($)')),
                ('banco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Banco ($)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo de caja',
                'verbose_name_plural': 'Saldo de caja',
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', '💵 Efectivo'), ('banco', '🏦 Banco'), ('ambas', '🔀 Ambas')], default='efectivo', max_length=10, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='monto_banco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto banco ($)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto efectivo ($)'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total ($)'),
        ),
    ]
