# Generated by Django 5.0.6 on 2026-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_saldocaja_egreso_forma_pago_egreso_monto_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de imagen'),
        ),
    ]
