# Generated by Django 5.0.6 on 2026-06-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='monto_prestamo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto préstamo ($)'),
        ),
        migrations.AddField(
            model_name='saldocaja',
            name='prestamo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Préstamo ($)'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', '💵 Efectivo'), ('banco', '🏦 Tarjeta / Banco'), ('ambas', '🔀 Ambas'), ('prestamo', '🤝 Préstamo')], default='efectivo', max_length=20, verbose_name='Forma de pago'),
        ),
    ]
