# Generated by Django 5.0.6 on 2026-06-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_egreso_monto_prestamo_saldocaja_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agregado', '🤝 Préstamo agregado'), ('cobro', '💸 Cobro de préstamo'), ('ajuste', '✏️ Ajuste manual')], max_length=20, verbose_name='Tipo de movimiento')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto ($)')),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto efectivo ($)')),
                ('monto_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto banco ($)')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Movimiento de préstamo',
                'verbose_name_plural': 'Movimientos de préstamos',
                'ordering': ['-fecha'],
            },
        ),
    ]
