# Generated by Django 5.0.6 on 2026-06-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_movimientoprestamo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoPrestamo',
        ),
        migrations.AddField(
            model_name='saldocaja',
            name='nota_prestamo',
            field=models.TextField(blank=True, verbose_name='Nota de préstamo'),
        ),
    ]
