# Generated by Django 5.2.11 on 2026-06-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_delete_movimientoprestamo_saldocaja_nota_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tendencia',
            field=models.BooleanField(default=False, verbose_name='En tendencia'),
        ),
    ]
