# Generated by Django 5.0.6 on 2026-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comentario / personalización'),
        ),
    ]
